alter table REPORT_GROUP add SYS_TENANT_ID varchar2(255)^
alter table REPORT_REPORT add SYS_TENANT_ID varchar2(255)^

drop index IDX_REPORT_GROUP_UNIQ_TITLE^
create unique index IDX_REPORT_GROUP_UNIQ_TITLE on REPORT_GROUP(TITLE, SYS_TENANT_ID, DELETE_TS)^

drop index IDX_REPORT_REPORT_UNIQ_NAME^
create unique index IDX_REPORT_REPORT_UNIQ_NAME on REPORT_REPORT(NAME, SYS_TENANT_ID, DELETE_TS)^