language: java
jdk: openjdk8

before_install:
  - git clone https://github.com/cuba-platform/cuba-gradle-plugin.git $TRAVIS_BUILD_DIR/../cuba-gradle-plugin
  - git clone https://github.com/cuba-platform/cuba.git $TRAVIS_BUILD_DIR/../cuba
  - (cd $TRAVIS_BUILD_DIR/../cuba-gradle-plugin && git checkout release_7_1)
  - (cd $TRAVIS_BUILD_DIR/../cuba && git checkout release_7_1)
  - (cd $TRAVIS_BUILD_DIR/../cuba-gradle-plugin && chmod +x ./gradlew && ./gradlew --no-daemon install)
  - (cd $TRAVIS_BUILD_DIR/../cuba && chmod +x ./gradlew && ./gradlew --no-daemon install)
  - chmod +x ./gradlew

install:
  - ./gradlew --no-daemon assemble

before_script:
  - psql -c 'create user root with password $$root$$; alter user root with superuser;' -U postgres

script:
  - ./gradlew --no-daemon createTestDb test javadoc

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - openjdk-8-jdk
  postgresql: "9.6"

services:
  - postgresql