alter table REPORT_REPORT add DELETE_TS timestamp^
alter table REPORT_REPORT add DELETED_BY varchar2(50)^

alter table REPORT_GROUP add DELETE_TS timestamp^
alter table REPORT_GROUP add DELETED_BY varchar2(50)^

alter table REPORT_TEMPLATE add DELETE_TS timestamp^
alter table REPORT_TEMPLATE add DELETED_BY varchar2(50)^

DECLARE
    i INTEGER;
BEGIN
  SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'IDX_REPORT_REPORT_UNIQ_NAME';
  IF i = 1 THEN
      EXECUTE IMMEDIATE 'drop index IDX_REPORT_REPORT_UNIQ_NAME';
      EXECUTE IMMEDIATE 'create unique index IDX_REPORT_REPORT_UNIQ_NAME on REPORT_REPORT (NAME, DELETE_TS)';
  END IF;
END;^

DECLARE
    i INTEGER;
BEGIN
  SELECT COUNT(*) INTO i FROM user_indexes WHERE index_name = 'IDX_REPORT_GROUP_UNIQ_TITLE';
  IF i = 1 THEN
      EXECUTE IMMEDIATE 'drop index IDX_REPORT_GROUP_UNIQ_TITLE';
      EXECUTE IMMEDIATE 'create unique index IDX_REPORT_GROUP_UNIQ_TITLE on REPORT_GROUP (TITLE, DELETE_TS)';
  END IF;
END;^